spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:db/mybatis/config.xml

wxshop:
  orderService:
    version: 1.0.0
    url: ""

dubbo:
  application:
    name: wxshop-main
  registry:
    address: zookeeper://127.0.0.1:2181

shiro-redis:
  redis-manager:
    host: 127.0.0.1:6379